"""empty message

Revision ID: 0d9097787b2c
Revises: 625195f96fa5
Create Date: 2026-02-27 17:55:05.856417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9097787b2c'
down_revision = '625195f96fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_repartidor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'delivery', ['id_repartidor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_repartidor')

    # ### end Alembic commands ###
