"""empty message

Revision ID: 0f20f7e9c9f6
Revises: a0b81a9d7865
Create Date: 2026-02-06 09:53:52.845371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f20f7e9c9f6'
down_revision = 'a0b81a9d7865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###
