"""add categorias and categoria_libro

Revision ID: 108e2b53138f
Revises: 75dcd453ac07
Create Date: 2026-02-05 12:54:46.857676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108e2b53138f'
down_revision = '02b805816baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=False)

    op.create_table('categoria_libro',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('categoria_id', 'libro_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categoria_libro')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))

    op.drop_table('categorias')
    op.drop_table('book')
    # ### end Alembic commands ###
