"""empty message

Revision ID: 48a18c11c26b
Revises: f5d48ea6c511
Create Date: 2026-02-06 11:39:11.732684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a18c11c26b'
down_revision = 'f5d48ea6c511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
