"""crear tabla provider_book

Revision ID: 522b329bc25c
Revises: 846d9af11e53
Create Date: 2026-02-12 12:10:38.748059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522b329bc25c'
down_revision = '846d9af11e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_book')
    # ### end Alembic commands ###