"""empty message

Revision ID: 568b826e18c2
Revises: 846d9af11e53
Create Date: 2026-02-12 21:04:09.804125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568b826e18c2'
down_revision = '846d9af11e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
