"""empty message

Revision ID: 5a993f6e75cd
Revises: 918087ee918e
Create Date: 2026-02-27 10:25:55.560754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a993f6e75cd'
down_revision = '918087ee918e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_titulo', sa.String(length=255), nullable=False),
    sa.Column('libro_autor', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor_notificaciones')
    # ### end Alembic commands ###
