"""empty message

Revision ID: 61b8a750fb93
Revises: 0763d677d453
Create Date: 2026-02-02 11:04:40.058731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b8a750fb93'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_providers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_providers_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_nombre'))
        batch_op.drop_index(batch_op.f('ix_providers_email'))
        batch_op.drop_index(batch_op.f('ix_providers_documento'))

    op.drop_table('providers')
    # ### end Alembic commands ###
