"""empty message

Revision ID: 7325550e7378
Revises: de0cf65e9eaf
Create Date: 2026-02-04 14:22:09.611487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7325550e7378'
down_revision = 'de0cf65e9eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_books')
    # ### end Alembic commands ###
