"""initial

<<<<<<<< HEAD:migrations/versions/02b805816baf_.py
Revision ID: 02b805816baf
Revises: 
Create Date: 2026-02-04 10:13:12.175833
========
Revision ID: 75dcd453ac07
Revises: 
Create Date: 2026-02-04 09:48:42.775244
>>>>>>>> develop:migrations/versions/75dcd453ac07_initial.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dcd453ac07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('titulo', sa.String(length=255), nullable=False),
                    sa.Column('autor', sa.String(length=255), nullable=False),
                    sa.Column('isbn', sa.String(length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('isbn')
                    )
    op.create_table('providers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(length=150), nullable=False),
                    sa.Column('email', sa.String(length=150), nullable=True),
                    sa.Column('telefono', sa.String(length=20), nullable=True),
                    sa.Column('password', sa.String(
                        length=300), nullable=False),
                    sa.Column('documento', sa.String(
                        length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_documento'), [
                              'documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_providers_email'), [
                              'email'], unique=True)
        batch_op.create_index(batch_op.f('ix_providers_nombre'), [
                              'nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_nombre'))
        batch_op.drop_index(batch_op.f('ix_providers_email'))
        batch_op.drop_index(batch_op.f('ix_providers_documento'))

    op.drop_table('providers')
    op.drop_table('book')
    # ### end Alembic commands ###
