"""add provider_book_id to cart_books

Revision ID: 7a760c4b1c56
Revises: 7dbb863cba5a
Create Date: 2026-02-18 14:24:32.053036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a760c4b1c56'
down_revision = '7dbb863cba5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_book_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'provider_book', ['provider_book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('provider_book_id')

    # ### end Alembic commands ###
