"""empty message

Revision ID: 967f37c0df42
Revises: 48a18c11c26b
Create Date: 2026-02-06 11:45:25.537319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967f37c0df42'
down_revision = '48a18c11c26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
