"""empty message

Revision ID: a0b81a9d7865
Revises: 108e2b53138f
Create Date: 2026-02-05 12:57:07.533963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b81a9d7865'
down_revision = '108e2b53138f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=350), nullable=False))
        batch_op.create_index(batch_op.f('ix_categorias_descripcion'), ['descripcion'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_descripcion'))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
