"""empty message

Revision ID: b6a9c7e5c740
Revises: 0ae3bffabfba
Create Date: 2026-02-18 10:21:43.164073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a9c7e5c740'
down_revision = '0ae3bffabfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=True))
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.drop_index(batch_op.f('ix_provider_nombre'))
        batch_op.create_index(batch_op.f('ix_provider_name'), ['name'], unique=False)
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_provider_name'))
        batch_op.create_index(batch_op.f('ix_provider_nombre'), ['nombre'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
