"""empty message

Revision ID: c6b9a46555cf
Revises: f8a3e61f5bff
Create Date: 2026-02-11 17:15:54.754361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b9a46555cf'
down_revision = 'f8a3e61f5bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password', sa.String(length=200), nullable=True))

        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=255),
                              type_=sa.String(length=120),
                              existing_nullable=False)
        batch_op.drop_constraint(batch_op.f(
            'delivery_identificacion_key'), type_='unique')
        batch_op.drop_column('apellido')
        batch_op.drop_column('identificacion')
        batch_op.drop_column('nombre')
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(
            length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text(
            "'delivery'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(
            length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('identificacion', sa.VARCHAR(
            length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(
            length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('delivery_identificacion_key'), [
                                          'identificacion'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
                              existing_type=sa.String(length=120),
                              type_=sa.VARCHAR(length=255),
                              existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
