"""empty message

Revision ID: d21d2c5138b6
Revises: 
Create Date: 2026-02-20 10:26:22.030340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d2c5138b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('portada', sa.String(length=300), nullable=True),
    sa.Column('categorias', sa.String(length=300), nullable=True),
    sa.Column('fecha_publicacion', sa.String(length=20), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=350), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_descripcion'), ['descripcion'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('identificacion', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_provider_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_provider_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='client', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_libro',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('categoria_id', 'libro_id')
    )
    op.create_table('provider_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_libro'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('provider_book_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_libro'], ['book.id'], ),
    sa.ForeignKeyConstraint(['provider_book_id'], ['provider_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('cart_books')
    op.drop_table('review')
    op.drop_table('provider_book')
    op.drop_table('categoria_libro')
    op.drop_table('carts')
    op.drop_table('addresses')
    op.drop_table('user')
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_name'))
        batch_op.drop_index(batch_op.f('ix_provider_email'))
        batch_op.drop_index(batch_op.f('ix_provider_documento'))

    op.drop_table('provider')
    op.drop_table('delivery')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))
        batch_op.drop_index(batch_op.f('ix_categorias_descripcion'))

    op.drop_table('categorias')
    op.drop_table('book')
    # ### end Alembic commands ###
