"""empty message

Revision ID: f50023e03622
Revises: fd111a69dd52
Create Date: 2026-02-16 01:15:49.130334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50023e03622'
down_revision = 'fd111a69dd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_books_id_carrito_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'carts', ['id_carrito'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_books_id_carrito_fkey'), 'carts', ['id_carrito'], ['id'])

    # ### end Alembic commands ###
