"""empty message

Revision ID: fd111a69dd52
Revises: a84b05abc617
Create Date: 2026-02-16 01:12:15.657989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd111a69dd52'
down_revision = 'a84b05abc617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('addresses_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id_usuario'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carts_id_cliente_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id_cliente'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_id_cliente_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id_cliente'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_id_cliente_fkey'), 'user', ['id_cliente'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('carts_id_cliente_fkey'), 'user', ['id_cliente'], ['id'])

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('addresses_id_usuario_fkey'), 'user', ['id_usuario'], ['id'])

    # ### end Alembic commands ###
